In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split,cross_validate,ShuffleSplit
from sklearn.metrics import r2_score,mean_absolute_error,mean_absolute_percentage_error,mean_squared_error,confusion_matrix,classification_report
from pandas_profiling import ProfileReport
from sklearn.linear_model import LogisticRegression,LogisticRegressionCV
from sklearn.preprocessing import StandardScaler,OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeClassifier


In [52]:
df=sns.load_dataset("penguins")
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [53]:
print(df.flipper_length_mm.isnull().sum())
print(df.bill_depth_mm.isnull().sum())
print(df.body_mass_g.isnull().sum())
print(df.bill_length_mm.isnull().sum())

2
2
2
2


In [54]:
df.info()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [61]:
oe=OrdinalEncoder()
df.island=oe.fit_transform(df[["island"]])

In [62]:
si=SimpleImputer()
A=si.fit_transform(df[["bill_length_mm",	"bill_depth_mm",	"flipper_length_mm",	"body_mass_g","island"]])

In [71]:
x=pd.DataFrame(A,columns=["bill_length_mm",	"bill_depth_mm",	"flipper_length_mm",	"body_mass_g","island"])

In [72]:
y=pd.DataFrame(oe.fit_transform(df[["species"]]))

In [74]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=0,test_size=0.25)

In [78]:
model2=make_pipeline(StandardScaler(),LogisticRegression())
model2.fit(xtrain,ytrain)


ypre=model2.predict(xtest)
print(confusion_matrix(ytest,ypre))
print(classification_report(ytest,ypre))

[[42  0  0]
 [ 1 13  0]
 [ 0  0 30]]
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99        42
         1.0       1.00      0.93      0.96        14
         2.0       1.00      1.00      1.00        30

    accuracy                           0.99        86
   macro avg       0.99      0.98      0.98        86
weighted avg       0.99      0.99      0.99        86



c:\Users\Lenovo\.conda\envs\ml\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
model2=tree()
model2.fit(xtrain,ytrain)


ypre=model2.predict(xtest)
print(confusion_matrix(ytest,ypre))
print(classification_report(ytest,ypre))