In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split,cross_validate,ShuffleSplit
from sklearn.metrics import r2_score,mean_absolute_error,mean_absolute_percentage_error,mean_squared_error,confusion_matrix,classification_report
from pandas_profiling import ProfileReport
from sklearn.linear_model import LogisticRegression,LogisticRegressionCV
from sklearn.preprocessing import StandardScaler,OrdinalEncoder
from sklearn.pipeline import make_pipeline

In [9]:
url="https://raw.githubusercontent.com/digipodium/Datasets/main/classfication/Social_Network_Ads.csv"
df=pd.read_csv(url)
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [10]:
ord=OrdinalEncoder()
df.Gender=ord.fit_transform(df[["Gender"]])
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510     1.0   19            19000          0
1  15810944     1.0   35            20000          0
2  15668575     0.0   26            43000          0
3  15603246     0.0   27            57000          0
4  15804002     1.0   19            76000          0

In [11]:
x=df[["Age","EstimatedSalary"]]
y=df.Purchased
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=0,test_size=.25)

In [12]:
model=LogisticRegression()
model.fit(xtrain,ytrain)
ypre=model.predict(xtest)
confusion_matrix(ytest,ypre)

array([[68,  0],
       [32,  0]], dtype=int64)

In [13]:
print(classification_report(ytest,ypre))


              precision    recall  f1-score   support

           0       0.68      1.00      0.81        68
           1       0.00      0.00      0.00        32

    accuracy                           0.68       100
   macro avg       0.34      0.50      0.40       100
weighted avg       0.46      0.68      0.55       100



c:\Users\Lenovo\.conda\envs\ml\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Lenovo\.conda\envs\ml\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Lenovo\.conda\envs\ml\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


<h1>With Scaling</h1>

In [14]:
model1=make_pipeline(StandardScaler(),LogisticRegression())
model1.fit(xtrain,ytrain)

ypre=model1.predict(xtest)
print(confusion_matrix(ytest,ypre))
print(classification_report(ytest,ypre))

[[65  3]
 [ 8 24]]
              precision    recall  f1-score   support

           0       0.89      0.96      0.92        68
           1       0.89      0.75      0.81        32

    accuracy                           0.89       100
   macro avg       0.89      0.85      0.87       100
weighted avg       0.89      0.89      0.89       100



In [15]:
model2=make_pipeline(StandardScaler(),LogisticRegressionCV())
model2.fit(xtrain,ytrain)


ypre=model2.predict(xtest)
print(confusion_matrix(ytest,ypre))
print(classification_report(ytest,ypre))

[[65  3]
 [ 8 24]]
              precision    recall  f1-score   support

           0       0.89      0.96      0.92        68
           1       0.89      0.75      0.81        32

    accuracy                           0.89       100
   macro avg       0.89      0.85      0.87       100
weighted avg       0.89      0.89      0.89       100



In [18]:
age=int(input(" "))
gen=input(" ")
sal=int(input(" "))

In [19]:
gen=ord.transform([[gen]])[0]
gen

c:\Users\Lenovo\.conda\envs\ml\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([1.])

In [22]:
imp=np.array([age,sal,gen])

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2664\2332930886.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  imp=np.array([age,sal,gen])
